[project]
name = "autonomous-software-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "kumargautam802108@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=4.0.3",
    "langgraph>=1.2.11",
    "ollama>=0.6.2",
]

[project.scripts]
autonomous-software-agent = "agent.cli:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "agent"
